# Generated by Django 5.0.7 on 2024-07-14 21:01

import common.utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "updated_by_ip",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "username",
                    models.TextField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. Should be a syntactically valid email.",
                        unique=True,
                        validators=[django.core.validators.EmailValidator],
                        verbose_name="username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator],
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=common.utils.get_upload_path
                    ),
                ),
                ("phone", models.CharField(max_length=30)),
                ("post_code", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=255)),
                ("is_verified", models.BooleanField(default=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities_light.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities_light.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to="core.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="updated_by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Users",
            },
        ),
    ]
